# Generated by Django 6.0.6 on 2026-07-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
