# Generated by Django 6.0.6 on 2026-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evallog',
            name='request_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
